### ISSUE TITLE
Refactor and clean up

### ISSUE THREAD

**Issue by Jakobis** [jlndk/devoops#57]
Squeaky clean plz
- [x] Make sure namespaces are consistant and proper
- [x] Code of higher quality (in terms of functionality and cleanliness)
- [x] Remove Unused projects
- [x] Docker and docker-compose config
    - [x] Persist database between shutdowns
    - [x] Close ports to DB in docker compose (fixed by making a development environment)
    - [x] Connection string from docker compose (config file or docker-compose.yml)
- [x] DevOps stuff (don't ask me what)
- [x] Etc.

**Comment by tobloef** [comment]
#62 Completed some of these items. @jlndk do you need to look at the other two perhaps?

**Comment by jlndk** [comment]
Can do
